pipeline {
  agent any
  stages {
    stage('Setup') {
      steps {
        sh '''../scripts/docker-setup.sh
'''
      }
    }

    stage('Clean') {
      steps {
        sh '../scripts/docker-clean.sh'
      }
    }

  }
}