pipeline {
  agent any
  stages {
    stage('Setup') {
      steps {
        sh '''chmod +x ./scripts/docker-setup.sh
sh ./scripts/docker-setup.sh'''
      }
    }

    stage('Clean') {
      steps {
        sh '''chmod +x ./scripts/docker-clean.sh
sh ./scripts/docker-clean.sh'''
      }
    }

    stage('Initial') {
      steps {
        sh '''chmod +x ./scripts/terraform-setup.sh
sh ./scripts/terraform-setup.sh
'''
      }
    }

  }
}