pipeline {
  agent any
  stages {
    stage('Setup') {
      steps {
        sh '''chmod +x ./scripts/docker-setup.sh
sh ./scripts/docker-setup.sh'''
      }
    }

    stage('Clean') {
      steps {
        sh '''chmod +x ./scripts/docker-clean.sh
sh ./scripts/docker-clean.sh'''
      }
    }

    stage('Initial') {
      agent {
        docker {
          image 'hashicorp/terraform:latest'
          args '--entrypoint='
        }

      }
      steps {
withCredentials([[ $class: 'AmazonWebServicesCredentialsBinding', credentialsId: "2ed37a50-3cfc-47a6-a0b5-fea04262838d", accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) { aws configure }
        }
      }

    }
  }
